# Generated by Django 4.2.4 on 2023-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_auto_20230830_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
