# Generated by Django 4.2.4 on 2023-08-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0003_alter_dform_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dform',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dform',
            name='message',
            field=models.CharField(max_length=50),
        ),
    ]
